
final List<String> videoURLs = [
    "https://youtu.be/mkTrbmr9TOg?si=https://youtu.be/mkTrbmr9TOg?si=MmXVivyJGiAgxsvi",
    "https://youtu.be/tfVb3fq4NmE?si=pfvfiz0-QHqElCPK",
    "https://youtu.be/ciPj2Bl-P-A?si=Ya6krwV10TDL2orI",
    "https://youtu.be/mkTrbmr9TOg?si=https://youtu.be/mkTrbmr9TOg?si=MmXVivyJGiAgxsvi",
    "https://youtu.be/tfVb3fq4NmE?si=pfvfiz0-QHqElCPK",
    "https://youtu.be/ciPj2Bl-P-A?si=Ya6krwV10TDL2orI",
    "https://youtu.be/mkTrbmr9TOg?si=https://youtu.be/mkTrbmr9TOg?si=MmXVivyJGiAgxsvi",
    "https://youtu.be/tfVb3fq4NmE?si=pfvfiz0-QHqElCPK",
    "https://youtu.be/ciPj2Bl-P-A?si=Ya6krwV10TDL2orI",
    "https://youtu.be/mkTrbmr9TOg?si=https://youtu.be/mkTrbmr9TOg?si=MmXVivyJGiAgxsvi",
    "https://youtu.be/tfVb3fq4NmE?si=pfvfiz0-QHqElCPK",
    "https://youtu.be/ciPj2Bl-P-A?si=Ya6krwV10TDL2orI",
    "https://youtu.be/mkTrbmr9TOg?si=https://youtu.be/mkTrbmr9TOg?si=MmXVivyJGiAgxsvi",
    "https://youtu.be/tfVb3fq4NmE?si=pfvfiz0-QHqElCPK",
    "https://youtu.be/ciPj2Bl-P-A?si=Ya6krwV10TDL2orI",
    "https://youtu.be/mkTrbmr9TOg?si=https://youtu.be/mkTrbmr9TOg?si=MmXVivyJGiAgxsvi",
    "https://youtu.be/tfVb3fq4NmE?si=pfvfiz0-QHqElCPK",
    "https://youtu.be/ciPj2Bl-P-A?si=Ya6krwV10TDL2orI",
    
  
  ];
  final List<String> videoTitles = [
    'Missed',
    'Open Wound',
    'Unsaid',
    'Missed',
    'Open Wound',
    'Unsaid',
    'Missed',
    'Open Wound',
    'Unsaid',
    'Missed',
    'Open Wound',
    'Unsaid',
    'Missed',
    'Open Wound',
    'Unsaid',
    'Missed',
    'Open Wound',
    'Unsaid',
  ];
  final List<String> videoSinger = [
    'Suly Pheng feat. KZ',
    'Suly Pheng feat. Pich Solikah',
    'Suly Pheng feat. KZ',
    'Suly Pheng feat. KZ',
    'Suly Pheng feat. Pich Solikah',
    'Suly Pheng feat. KZ',
    'Suly Pheng feat. KZ',
    'Suly Pheng feat. Pich Solikah',
    'Suly Pheng feat. KZ',
    'Suly Pheng feat. KZ',
    'Suly Pheng feat. Pich Solikah',
    'Suly Pheng feat. KZ',
    'Suly Pheng feat. KZ',
    'Suly Pheng feat. Pich Solikah',
    'Suly Pheng feat. KZ',
    'Suly Pheng feat. KZ',
    'Suly Pheng feat. Pich Solikah',
    'Suly Pheng feat. KZ',
  ];
  final List<String> videoViews = [
    'Khmer • 1.4M views',
    'Khmer • 12M views',
    'Khmer • 10M views',
    'Khmer • 1.4M views',
    'Khmer • 12M views',
    'Khmer • 10M views',
    'Khmer • 1.4M views',
    'Khmer • 12M views',
    'Khmer • 10M views',
    'Khmer • 1.4M views',
    'Khmer • 12M views',
    'Khmer • 10M views',
    'Khmer • 1.4M views',
    'Khmer • 12M views',
    'Khmer • 10M views',
    'Khmer • 1.4M views',
    'Khmer • 12M views',
    'Khmer • 10M views',
  ];